import type { Metadata } from "next";
import { Comic_Neue, Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/shared/Navbar";
import WorkoutProvider from "@/contexts/WorkoutContext";
import { ToastContainer } from "react-toastify";
import Footer from "@/Components/shared/Footer";

export const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400"],
});

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <WorkoutProvider>
          <header className="sticky top-0 z-50">
            <Navbar></Navbar>
          </header>
          <main className="px-8">{children}</main>
          <Footer></Footer>
        </WorkoutProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
